### ISSUE TITLE
Carthage support broken

### ISSUE THREAD

**Issue by apocolipse** [andysmart/Timberjack#1]
Scheme isn't marked as shared, so carthage support is currently broken.

**Comment by andrewjackman** [comment]
I've created a pull request to fix this issue: andrewjackman@bf14cfe3cb837cf8d22bf74fff6cfc2c209f33ea

**Comment by andysmart** [comment]
Thanks @andrewjackman. Fixed in #2

**Comment by andrewjackman** [comment]
No problem. Don't forget to tag that change otherwise Carthage won't pick up the correct version.

**Comment by MartijnSchoemaker** [comment]
Still get this error when using carthage:
Dependency "Timberjack" has no shared framework schemes for any of the platforms: iOS
